version: '3.8'

networks:
  monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.31.0.8/29"
          gateway: "172.31.0.9"

volumes:
  prometheus_data: {}

services:
  google-wifi:
    image: nysasounds/google-wifi-prometheus-exporter:0.0.1
    container_name: google-wifi
    restart: unless-stopped
    expose:
      - 9469
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: google-wifi-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=7d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
