global:
  scrape_interval: 5m

scrape_configs:
  - job_name: 'google-wifi'
    static_configs:
      - targets:
        - "google-wifi:9469"
    metrics_path: "/probe"
    params:
      script: ["google-wifi"]
    scrape_timeout: "1m"
    relabel_configs:
      - target_label: script
        replacement: google-wifi

remote_write:
- url: https://prometheus-server
  bearer_token: some-super-secret-token
